import { useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { ADMIN_TOKEN_KEY, ADMIN_USER_KEY, API_URL } from "../services/api";

export default function AdminLogin() {
    const [email, setEmail] = useState(""), [password, setPassword] = useState(""), [show, setShow] = useState(false), [error, setError] = useState(""), [loading, setLoading] = useState(false), navigate = useNavigate();
    if (localStorage.getItem(ADMIN_TOKEN_KEY)) return <Navigate to="/admin/dashboard" replace />;
    const submit = async (event) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch(`${API_URL}/admin/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); localStorage.setItem(ADMIN_TOKEN_KEY, data.token); localStorage.setItem(ADMIN_USER_KEY, JSON.stringify(data.user)); navigate("/admin/dashboard"); } catch (e) { setError(e.message || "Unable to sign in"); } finally { setLoading(false); } };
    return <main className="grid min-h-screen place-items-center bg-gradient-to-br from-slate-950 to-slate-700 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-8 shadow-2xl"><div className="mb-7 text-center"><p className="text-3xl">🍔</p><h1 className="mt-2 text-2xl font-bold">FoodExpress Admin</h1><p className="mt-1 text-sm text-slate-500">Sign in with an administrator account</p></div>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="mb-4 block text-sm font-medium">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1 w-full rounded-lg border p-3 outline-amber-500" /></label><label className="block text-sm font-medium">Password<div className="relative mt-1"><input required type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} className="w-full rounded-lg border p-3 pr-16 outline-amber-500"/><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-3 text-sm text-slate-500">{show ? "Hide" : "Show"}</button></div></label><button disabled={loading} className="mt-6 w-full rounded-lg bg-amber-400 py-3 font-semibold text-slate-900 disabled:opacity-60">{loading ? "Signing in..." : "Login"}</button></form></main>;
}
